apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: diabetes
        image: baehanjin/diabetes
        ports:
        - containerPort: 5000