apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalp-api
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: scalp-api
        image: baehanjin/scalp_ai_api:1
        ports:
        - containerPort: 8021